--------------------------------------------------------
--  File created - Monday-November-28-2022   
--------------------------------------------------------
@/Users/baeseongho/Downloads/KJ/SEQUENCES/SEQ_SYS_FILE.sql
@/Users/baeseongho/Downloads/KJ/SEQUENCES/SEQ_SYS_FILE_TEMP.sql
@/Users/baeseongho/Downloads/KJ/TABLES/CM0060T.sql
@/Users/baeseongho/Downloads/KJ/TABLES/CM0070T.sql
@/Users/baeseongho/Downloads/KJ/TABLES/CM0075T.sql
@/Users/baeseongho/Downloads/KJ/TABLES/CM0077T.sql
@/Users/baeseongho/Downloads/KJ/TABLES/CM0079T.sql
@/Users/baeseongho/Downloads/KJ/TABLES/COMP_DUP_INFO.sql
@/Users/baeseongho/Downloads/KJ/TABLES/C_0005.sql
@/Users/baeseongho/Downloads/KJ/TABLES/C_0010.sql
@/Users/baeseongho/Downloads/KJ/TABLES/C_0011_NEW.sql
@/Users/baeseongho/Downloads/KJ/TABLES/C_0020.sql
@/Users/baeseongho/Downloads/KJ/TABLES/C_0020_221107.sql
@/Users/baeseongho/Downloads/KJ/TABLES/C_0030.sql
@/Users/baeseongho/Downloads/KJ/TABLES/C_0031.sql
@/Users/baeseongho/Downloads/KJ/TABLES/C_0040.sql
@/Users/baeseongho/Downloads/KJ/TABLES/C_0041.sql
@/Users/baeseongho/Downloads/KJ/TABLES/C_0042.sql
@/Users/baeseongho/Downloads/KJ/TABLES/C_0043.sql
@/Users/baeseongho/Downloads/KJ/TABLES/C_0045.sql
@/Users/baeseongho/Downloads/KJ/TABLES/C_0046.sql
@/Users/baeseongho/Downloads/KJ/TABLES/C_0050.sql
@/Users/baeseongho/Downloads/KJ/TABLES/C_0050_221116.sql
@/Users/baeseongho/Downloads/KJ/TABLES/C_0051.sql
@/Users/baeseongho/Downloads/KJ/TABLES/C_0051_221116.sql
@/Users/baeseongho/Downloads/KJ/TABLES/C_0060.sql
@/Users/baeseongho/Downloads/KJ/TABLES/C_0061.sql
@/Users/baeseongho/Downloads/KJ/TABLES/C_2000.sql
@/Users/baeseongho/Downloads/KJ/TABLES/EXAM_USER_LIST.sql
@/Users/baeseongho/Downloads/KJ/TABLES/G_600.sql
@/Users/baeseongho/Downloads/KJ/TABLES/H_0100.sql
@/Users/baeseongho/Downloads/KJ/TABLES/LOGIN_ADDRESS.sql
@/Users/baeseongho/Downloads/KJ/TABLES/MAIL_MSG.sql
@/Users/baeseongho/Downloads/KJ/TABLES/MASTER_LANGUAGE.sql
@/Users/baeseongho/Downloads/KJ/TABLES/MM4015T.sql
@/Users/baeseongho/Downloads/KJ/TABLES/MM4030T.sql
@/Users/baeseongho/Downloads/KJ/TABLES/MM4035T.sql
@/Users/baeseongho/Downloads/KJ/TABLES/MM4045T.sql
@/Users/baeseongho/Downloads/KJ/TABLES/P_600.sql
@/Users/baeseongho/Downloads/KJ/TABLES/QIS_EXCEL_LOADER_EXR.sql
@/Users/baeseongho/Downloads/KJ/TABLES/QIS_UPLOAD_FILE.sql
@/Users/baeseongho/Downloads/KJ/TABLES/QIS_UPLOAD_FILE_LIST.sql
@/Users/baeseongho/Downloads/KJ/TABLES/Q_700.sql
@/Users/baeseongho/Downloads/KJ/TABLES/Q_701.sql
@/Users/baeseongho/Downloads/KJ/TABLES/Q_705.sql
@/Users/baeseongho/Downloads/KJ/TABLES/Q_705_NEW.sql
@/Users/baeseongho/Downloads/KJ/TABLES/Q_706.sql
@/Users/baeseongho/Downloads/KJ/TABLES/SYS_FILE_UPLOAD.sql
@/Users/baeseongho/Downloads/KJ/TABLES/SYS_FILE_UPLOAD_TEMP.sql
@/Users/baeseongho/Downloads/KJ/TABLES/S_2100.sql
@/Users/baeseongho/Downloads/KJ/TABLES/S_2500.sql
@/Users/baeseongho/Downloads/KJ/TABLES/S_2510.sql
@/Users/baeseongho/Downloads/KJ/TABLES/TEMP_LJS.sql
@/Users/baeseongho/Downloads/KJ/TABLES/WF_ACTIVITY.sql
@/Users/baeseongho/Downloads/KJ/TABLES/WF_CODE.sql
@/Users/baeseongho/Downloads/KJ/TABLES/WF_DOCS.sql
@/Users/baeseongho/Downloads/KJ/TABLES/WF_DOC_ROLES.sql
@/Users/baeseongho/Downloads/KJ/TABLES/XM000.sql
@/Users/baeseongho/Downloads/KJ/TABLES/XM000_REGI.sql
@/Users/baeseongho/Downloads/KJ/TABLES/XM000_SEARCH.sql
@/Users/baeseongho/Downloads/KJ/TABLES/XM001.sql
@/Users/baeseongho/Downloads/KJ/TABLES/XM001_LOGIN.sql
@/Users/baeseongho/Downloads/KJ/TABLES/XM010.sql
@/Users/baeseongho/Downloads/KJ/TABLES/XM604.sql
@/Users/baeseongho/Downloads/KJ/TABLES/XM605.sql
@/Users/baeseongho/Downloads/KJ/TABLES/XM606.sql
@/Users/baeseongho/Downloads/KJ/TABLES/XM607.sql
@/Users/baeseongho/Downloads/KJ/TABLES/XM800.sql
@/Users/baeseongho/Downloads/KJ/TABLES/XM900.sql
@/Users/baeseongho/Downloads/KJ/TABLES/XM900_221109.sql
@/Users/baeseongho/Downloads/KJ/VIEWS/V_COMPLET_DOC.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_CM0070T.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_XM001.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_C_0010.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_CM0079T.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_C_2000.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_C_0051.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_C_0050.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_XM605.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_MASTER_LANGUAGE.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/WF_DOC_ROLES_PK.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/WF_DOCS_PK.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/WF_ACTIVITY_PK.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_C_0040.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_C_0041.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_C_0043.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_C_0005.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_C_0031.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_C_0045.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_C_0046.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_C_0030.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_CM0060T.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_H_0100.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_C_0061.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_C_0060.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_XM606.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_XM607.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_WF_CODE.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_MAIL_MSG.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_P_600.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_TEMP_LJS.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_Q_700.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_XM000.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_COMP_DUP_INFO.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_XM000_REGI.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_XM000_SEARCH.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_Q_705_NEW.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_Q_705.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_Q_706.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_Q_701.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_XM800.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_XM900.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_C_0020.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_MM4030T.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_MM4035T.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_MM4015T.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_MM4045T.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_CM0077T.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_S_2100.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_S_2500.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_S_2510.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/SYS_FILE_UPLOAD_PK.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/SYS_FILE_UPLOAD_TEMP_PK.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/QIS_UPLOAD_FILE_LIST_PK.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/IDX_G_600_2.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/IX_G_600_01.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/IDX_G_600_5.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/IDX_XM605_1.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/IX_G_600_02.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_QIS_UPLOAD_FILE.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/SYS_FILE_UPLOAD_TEMP_IX01.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/IDX_G_600_7.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_P_600_2.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/SYS_FILE_UPLOAD_IX01.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/IDX_G_600_3.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/IDX_G_600_1.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/IDX_C_0010_1.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_CM0075T.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/IDX_G_600_4.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_C_0042.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/IDX_G_600_CAL.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/IDX_QIS_UPLOAD_FILE_1.sql
@/Users/baeseongho/Downloads/KJ/INDEXES/PK_G_600.sql
@/Users/baeseongho/Downloads/KJ/TRIGGERS/DT_QIS_UPLOAD_FILE.sql
@/Users/baeseongho/Downloads/KJ/TRIGGERS/QIS_UPLOAD_FILE_T1.sql
@/Users/baeseongho/Downloads/KJ/TRIGGERS/QIS_UPLOAD_FILE_T2.sql
@/Users/baeseongho/Downloads/KJ/PROCEDURES/APPROVAL_STATUS_COMMENT.sql
@/Users/baeseongho/Downloads/KJ/PROCEDURES/APPROVAL_STATUS_LIST.sql
@/Users/baeseongho/Downloads/KJ/PROCEDURES/APPROVAL_STATUS_REV.sql
@/Users/baeseongho/Downloads/KJ/PROCEDURES/BLOB_TO_FILE.sql
@/Users/baeseongho/Downloads/KJ/PROCEDURES/CHECKLOGIN.sql
@/Users/baeseongho/Downloads/KJ/PROCEDURES/GET_TEAM_LIST.sql
@/Users/baeseongho/Downloads/KJ/PROCEDURES/GET_XUSER_BY_TEAMCD.sql
@/Users/baeseongho/Downloads/KJ/PROCEDURES/LIST_YEAR.sql
@/Users/baeseongho/Downloads/KJ/PROCEDURES/LOGIN.sql
@/Users/baeseongho/Downloads/KJ/PROCEDURES/LOGOUT.sql
@/Users/baeseongho/Downloads/KJ/PROCEDURES/PASSWORD_.sql
@/Users/baeseongho/Downloads/KJ/PROCEDURES/SECUR_CONFIRM.sql
@/Users/baeseongho/Downloads/KJ/PROCEDURES/SHOW_ALERT.sql
@/Users/baeseongho/Downloads/KJ/PROCEDURES/SHOW_ERR.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/COMC0005.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/COMC0010.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/COMC0010_221122.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/COMC0010_BS.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/COMC0010_YC.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/COMC0030.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/COMC0031.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/COMC0031_221103.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/COMC0040.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/COMC0042.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/COMC0043.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/COMCATALOG.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/COMCURRENCY.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/COMMESSAGE.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/COMMON.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/COMMON_DHX6.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/COMWFCODE.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/COMXM001.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/COMXM607.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/DBV_GRID.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/EXR1010.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/EXR1010_YC.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/EXR1010_YC_2.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KB2B1107.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KB2B1108.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KB2B1110.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KB2B1111.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KB2B2102.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KB2B2103.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KB2B2104.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KB2B3102.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KB2B3103.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KB2B3107.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KB2B3108.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KB2B9104.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KB2B9106.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KB2B9106_KJA.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KB2B9107.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KB2B9107_NEW.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KB2B9108.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KB2B9111.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KB2B9112.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM1101.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM1102.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM1103.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM1104_A.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM1105_A.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM1106_A.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM2101.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM2102.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM2103.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM2104.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM2106.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM2107.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM2201.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM2202.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM2203.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM2204.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM2205.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM2206.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM3101.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM3102.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM3103.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM3104.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM4102.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM4103.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM4104.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM4105.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM4111.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM4112.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM4113.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM4114.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM4118.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM5112.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM5113.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM5114.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM5117.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM5118.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM6101.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM6102.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM6103.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM6104.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM6105.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM6106.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM7101.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM7102.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM8201.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM8202.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM8203.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM9101.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/KSCM9102.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/MAIL_MSG_PKG.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/MAIN_KAPS.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/SAMPLE_ATTACHFORM.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/SAMPLE_CHART.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/SAMPLE_PKG.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/SAMPLE_TEMPLATE.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/WFING_K.sql
@/Users/baeseongho/Downloads/KJ/PACKAGES/WFWAIT_K.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/COMC0005.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/COMC0010.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/COMC0010_221122.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/COMC0010_BS.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/COMC0010_YC.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/COMC0030.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/COMC0031.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/COMC0031_221103.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/COMC0040.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/COMC0042.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/COMC0043.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/COMCATALOG.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/COMCURRENCY.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/COMMESSAGE.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/COMMON.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/COMMON_DHX6.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/COMWFCODE.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/COMXM001.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/COMXM607.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/DBV_GRID.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/EXR1010.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/EXR1010_YC.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/EXR1010_YC_2.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KB2B1107.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KB2B1108.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KB2B1110.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KB2B1111.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KB2B2102.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KB2B2103.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KB2B2104.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KB2B3102.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KB2B3103.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KB2B3107.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KB2B3108.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KB2B9104.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KB2B9106.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KB2B9106_KJA.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KB2B9107.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KB2B9107_NEW.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KB2B9108.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KB2B9111.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KB2B9112.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM1101.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM1102.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM1103.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM1104_A.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM1105_A.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM1106_A.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM2101.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM2102.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM2103.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM2104.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM2106.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM2107.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM2201.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM2202.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM2203.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM2204.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM2205.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM2206.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM3101.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM3102.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM3103.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM3104.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM4102.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM4103.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM4104.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM4105.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM4111.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM4112.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM4113.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM4114.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM4118.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM5112.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM5113.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM5114.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM5117.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM5118.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM6101.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM6102.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM6103.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM6104.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM6105.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM6106.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM7101.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM7102.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM8201.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM8202.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM8203.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM9101.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/KSCM9102.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/MAIL_MSG_PKG.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/MAIN_KAPS.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/SAMPLE_ATTACHFORM.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/SAMPLE_CHART.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/SAMPLE_PKG.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/SAMPLE_TEMPLATE.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/WFING_K.sql
@/Users/baeseongho/Downloads/KJ/PACKAGE_BODIES/WFWAIT_K.sql
@/Users/baeseongho/Downloads/KJ/FUNCTIONS/CHECK_APPROVAL_NEW.sql
@/Users/baeseongho/Downloads/KJ/FUNCTIONS/CHECK_ROWID.sql
@/Users/baeseongho/Downloads/KJ/FUNCTIONS/CH_XML_DATA.sql
@/Users/baeseongho/Downloads/KJ/FUNCTIONS/GET_CATALOG_NAME.sql
@/Users/baeseongho/Downloads/KJ/FUNCTIONS/GET_COMPDATE.sql
@/Users/baeseongho/Downloads/KJ/FUNCTIONS/GET_DOC_STATUS.sql
@/Users/baeseongho/Downloads/KJ/FUNCTIONS/GET_FN.sql
@/Users/baeseongho/Downloads/KJ/FUNCTIONS/GET_MASTER_NAME.sql
@/Users/baeseongho/Downloads/KJ/FUNCTIONS/GET_PREMIER_UTIL.sql
@/Users/baeseongho/Downloads/KJ/FUNCTIONS/GET_PROGRAM_NAME.sql
@/Users/baeseongho/Downloads/KJ/FUNCTIONS/GET_ROLE.sql
@/Users/baeseongho/Downloads/KJ/FUNCTIONS/GET_SYSTYPE.sql
@/Users/baeseongho/Downloads/KJ/FUNCTIONS/GET_TEAMCD.sql
@/Users/baeseongho/Downloads/KJ/FUNCTIONS/GET_TEAM_NAME.sql
@/Users/baeseongho/Downloads/KJ/FUNCTIONS/GET_UNODE_CNT.sql
@/Users/baeseongho/Downloads/KJ/FUNCTIONS/GET_UNODE_LAST.sql
@/Users/baeseongho/Downloads/KJ/FUNCTIONS/GET_USER_NAME.sql
@/Users/baeseongho/Downloads/KJ/FUNCTIONS/RETURN_ENCODE_TEXT.sql
@/Users/baeseongho/Downloads/KJ/FUNCTIONS/RETURN_HTML_TEXT.sql
@/Users/baeseongho/Downloads/KJ/FUNCTIONS/URLENCODER.sql
@/Users/baeseongho/Downloads/KJ/FUNCTIONS/VAULT_DOWNLOAD.sql
@/Users/baeseongho/Downloads/KJ/FUNCTIONS/VAULT_GRID.sql
@/Users/baeseongho/Downloads/KJ/SYNONYMS/MDM0200.sql
@/Users/baeseongho/Downloads/KJ/SYNONYMS/MDM0200_HISTORY.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/MAIL_MSG.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/S_2500.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/Q_705_NEW.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/XM605.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/C_0045.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/WF_CODE.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/Q_701.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/G_600.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/XM900.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/C_2000.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/P_600.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/C_0041.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/C_0030.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/MASTER_LANGUAGE.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/C_0050.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/C_0060.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/CM0077T.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/XM001_LOGIN.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/WF_DOC_ROLES.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/CM0075T.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/XM606.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/XM607.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/SYS_FILE_UPLOAD.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/Q_706.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/WF_DOCS.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/TEMP_LJS.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/Q_700.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/C_0020.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/MM4045T.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/C_0010.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/MM4015T.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/MM4035T.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/C_0031.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/Q_705.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/C_0040.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/XM010.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/QIS_UPLOAD_FILE.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/COMP_DUP_INFO.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/XM000_SEARCH.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/H_0100.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/S_2510.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/C_0005.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/C_0061.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/C_0043.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/XM001.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/C_0051.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/C_0046.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/MM4030T.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/CM0070T.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/CM0060T.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/XM000.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/CM0079T.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/WF_ACTIVITY.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/S_2100.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/QIS_UPLOAD_FILE_LIST.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/XM900_221109.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/XM800.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/XM000_REGI.sql
@/Users/baeseongho/Downloads/KJ/CONSTRAINTS/SYS_FILE_UPLOAD_TEMP.sql
