--------------------------------------------------------
--  DDL for Index PK_CM0075T
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREMIER"."PK_CM0075T" ON "PREMIER"."CM0075T" ("COMPANYCD", "VENDCD", "BUSINO") 
  PCTFREE 5 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 393216 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_IDX" ;
