--------------------------------------------------------
--  DDL for Index PK_Q_706
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREMIER"."PK_Q_706" ON "PREMIER"."Q_706" ("KINDCD", "SECUR_TYPE", "COMPANYCD", "GUBUN", "XUSER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_IDX" ;
