--------------------------------------------------------
--  DDL for Index PK_XM001
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREMIER"."PK_XM001" ON "PREMIER"."XM001" ("COMPANYCD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_IDX" ;
