--------------------------------------------------------
--  DDL for Index WF_DOC_ROLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREMIER"."WF_DOC_ROLES_PK" ON "PREMIER"."WF_DOC_ROLES" ("DOC_ID", "ORG_ID", "EMP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 3145728 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_IDX" ;
