--------------------------------------------------------
--  Constraints for Table C_0061
--------------------------------------------------------

  ALTER TABLE "PREMIER"."C_0061" MODIFY ("SYSTEMCD" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."C_0061" MODIFY ("CATALOGCD" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."C_0061" MODIFY ("LANG" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."C_0061" MODIFY ("MESSAGE_TEXT" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."C_0061" ADD CONSTRAINT "PK_C_0061" PRIMARY KEY ("SYSTEMCD", "CATALOGCD", "LANG", "MESSAGE_TEXT")
  USING INDEX "PREMIER"."PK_C_0061"  ENABLE;
