--------------------------------------------------------
--  Constraints for Table G_600
--------------------------------------------------------

  ALTER TABLE "PREMIER"."G_600" ADD CHECK ("YY" IS NOT NULL) DISABLE;
  ALTER TABLE "PREMIER"."G_600" ADD CHECK ("G_GBN" IS NOT NULL) DISABLE;
  ALTER TABLE "PREMIER"."G_600" ADD CHECK ("G_COMPANYCD" IS NOT NULL) DISABLE;
  ALTER TABLE "PREMIER"."G_600" ADD CHECK ("G_CODE" IS NOT NULL) DISABLE;
  ALTER TABLE "PREMIER"."G_600" ADD CHECK ("COMPANYCD" IS NOT NULL) DISABLE;
  ALTER TABLE "PREMIER"."G_600" ADD CHECK ("GUBUN" IS NOT NULL) DISABLE;
  ALTER TABLE "PREMIER"."G_600" ADD CHECK ("XUSER" IS NOT NULL) DISABLE;
  ALTER TABLE "PREMIER"."G_600" ADD CHECK ("SNO" IS NOT NULL) DISABLE;
