--------------------------------------------------------
--  Constraints for Table MASTER_LANGUAGE
--------------------------------------------------------

  ALTER TABLE "PREMIER"."MASTER_LANGUAGE" MODIFY ("TABLEID" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."MASTER_LANGUAGE" MODIFY ("COMPANYCD" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."MASTER_LANGUAGE" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."MASTER_LANGUAGE" MODIFY ("GUBUN" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."MASTER_LANGUAGE" MODIFY ("LANG" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."MASTER_LANGUAGE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."MASTER_LANGUAGE" ADD CONSTRAINT "PK_MASTER_LANGUAGE" PRIMARY KEY ("TABLEID", "COMPANYCD", "CODE", "GUBUN", "LANG")
  USING INDEX "PREMIER"."PK_MASTER_LANGUAGE"  ENABLE;
