--------------------------------------------------------
--  Constraints for Table MM4015T
--------------------------------------------------------

  ALTER TABLE "PREMIER"."MM4015T" MODIFY ("COMPANYCD" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."MM4015T" MODIFY ("VENDCD" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."MM4015T" MODIFY ("INDATE" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."MM4015T" MODIFY ("APNO" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."MM4015T" ADD CONSTRAINT "PK_MM4015T" PRIMARY KEY ("COMPANYCD", "VENDCD", "INDATE", "APNO")
  USING INDEX "PREMIER"."PK_MM4015T"  ENABLE;
