--------------------------------------------------------
--  Constraints for Table QIS_UPLOAD_FILE_LIST
--------------------------------------------------------

  ALTER TABLE "PREMIER"."QIS_UPLOAD_FILE_LIST" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."QIS_UPLOAD_FILE_LIST" MODIFY ("FILE_NAME" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."QIS_UPLOAD_FILE_LIST" ADD CONSTRAINT "QIS_UPLOAD_FILE_LIST_PK" PRIMARY KEY ("NAME")
  USING INDEX "PREMIER"."QIS_UPLOAD_FILE_LIST_PK"  ENABLE;
