--------------------------------------------------------
--  Constraints for Table S_2100
--------------------------------------------------------

  ALTER TABLE "PREMIER"."S_2100" MODIFY ("COMPANYCD" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."S_2100" MODIFY ("VENDCD" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."S_2100" MODIFY ("YMD" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."S_2100" MODIFY ("CAPNO" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."S_2100" ADD CONSTRAINT "PK_S_2100" PRIMARY KEY ("COMPANYCD", "VENDCD", "YMD", "CAPNO")
  USING INDEX "PREMIER"."PK_S_2100"  ENABLE;
