--------------------------------------------------------
--  Constraints for Table S_2500
--------------------------------------------------------

  ALTER TABLE "PREMIER"."S_2500" MODIFY ("COMPANYCD" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."S_2500" MODIFY ("VENDCD" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."S_2500" MODIFY ("SVENDCD" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."S_2500" MODIFY ("SAUP" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."S_2500" MODIFY ("SYMD" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."S_2500" MODIFY ("PONO" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."S_2500" ADD CONSTRAINT "PK_S_2500" PRIMARY KEY ("COMPANYCD", "VENDCD", "SVENDCD", "SAUP", "SYMD", "PONO")
  USING INDEX "PREMIER"."PK_S_2500"  ENABLE;
