--------------------------------------------------------
--  Constraints for Table S_2510
--------------------------------------------------------

  ALTER TABLE "PREMIER"."S_2510" MODIFY ("COMPANYCD" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."S_2510" MODIFY ("VENDCD" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."S_2510" MODIFY ("SVENDCD" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."S_2510" MODIFY ("SAUP" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."S_2510" MODIFY ("SYMD" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."S_2510" MODIFY ("PONO" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."S_2510" MODIFY ("SNO" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."S_2510" ADD CONSTRAINT "PK_S_2510" PRIMARY KEY ("COMPANYCD", "VENDCD", "SVENDCD", "SAUP", "SYMD", "PONO", "SNO")
  USING INDEX "PREMIER"."PK_S_2510"  ENABLE;
