--------------------------------------------------------
--  Constraints for Table WF_DOC_ROLES
--------------------------------------------------------

  ALTER TABLE "PREMIER"."WF_DOC_ROLES" MODIFY ("DOC_ID" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."WF_DOC_ROLES" MODIFY ("COM_ID" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."WF_DOC_ROLES" MODIFY ("ORG_ID" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."WF_DOC_ROLES" MODIFY ("EMP_ID" NOT NULL ENABLE);
  ALTER TABLE "PREMIER"."WF_DOC_ROLES" ADD CONSTRAINT "WF_DOC_ROLES_PK" PRIMARY KEY ("DOC_ID", "ORG_ID", "EMP_ID")
  USING INDEX "PREMIER"."WF_DOC_ROLES_PK"  ENABLE;
