--------------------------------------------------------
--  DDL for Table C_0020
--------------------------------------------------------

  CREATE TABLE "PREMIER"."C_0020" 
   (	"COMPANYCD" VARCHAR2(2 BYTE), 
	"GUBUN" VARCHAR2(1 BYTE), 
	"XUSER" VARCHAR2(20 BYTE), 
	"SYSTEMCD" VARCHAR2(3 BYTE), 
	"GRADE" VARCHAR2(30 BYTE), 
	"USEYN" VARCHAR2(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;

   COMMENT ON COLUMN "PREMIER"."C_0020"."COMPANYCD" IS '광진구분 (00.광진상공, 01.광진기계)';
   COMMENT ON COLUMN "PREMIER"."C_0020"."GUBUN" IS '0:내부사번 1:업체코드';
   COMMENT ON COLUMN "PREMIER"."C_0020"."XUSER" IS '로그인코드';
   COMMENT ON COLUMN "PREMIER"."C_0020"."SYSTEMCD" IS '사용시스템';
   COMMENT ON COLUMN "PREMIER"."C_0020"."GRADE" IS '사용등급';
   COMMENT ON COLUMN "PREMIER"."C_0020"."USEYN" IS '사용유무 (Y.사용  N.사용안함)';
   COMMENT ON TABLE "PREMIER"."C_0020"  IS '로그인 시스템 사용등급';
