--------------------------------------------------------
--  DDL for Table C_0030
--------------------------------------------------------

  CREATE TABLE "PREMIER"."C_0030" 
   (	"SYSTEMCD" VARCHAR2(3 BYTE), 
	"GRADE" VARCHAR2(10 BYTE), 
	"DESCR" VARCHAR2(100 BYTE), 
	"USEYN" VARCHAR2(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;

   COMMENT ON COLUMN "PREMIER"."C_0030"."SYSTEMCD" IS '시스템코드';
   COMMENT ON COLUMN "PREMIER"."C_0030"."GRADE" IS '등급';
   COMMENT ON COLUMN "PREMIER"."C_0030"."DESCR" IS '내용';
   COMMENT ON COLUMN "PREMIER"."C_0030"."USEYN" IS '사용유무 (Y.사용  N.사용안함)';
   COMMENT ON TABLE "PREMIER"."C_0030"  IS '시스템 등급 마스타 (자식:C0031)';
