--------------------------------------------------------
--  DDL for Table C_0060
--------------------------------------------------------

  CREATE TABLE "PREMIER"."C_0060" 
   (	"SYSTEMCD" VARCHAR2(3 BYTE), 
	"CATALOGCD" VARCHAR2(30 BYTE), 
	"DESCR" VARCHAR2(500 BYTE), 
	"USEYN" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"MG_YN" VARCHAR2(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;

   COMMENT ON COLUMN "PREMIER"."C_0060"."SYSTEMCD" IS '시스템코드';
   COMMENT ON COLUMN "PREMIER"."C_0060"."CATALOGCD" IS 'Catalog';
   COMMENT ON COLUMN "PREMIER"."C_0060"."DESCR" IS '내용';
   COMMENT ON COLUMN "PREMIER"."C_0060"."USEYN" IS '사용유무';
   COMMENT ON TABLE "PREMIER"."C_0060"  IS 'Message 마스타 (자식:C_0061)';
