--------------------------------------------------------
--  DDL for Table C_0061
--------------------------------------------------------

  CREATE TABLE "PREMIER"."C_0061" 
   (	"SYSTEMCD" VARCHAR2(3 BYTE), 
	"CATALOGCD" VARCHAR2(30 BYTE), 
	"LANG" VARCHAR2(10 BYTE), 
	"MESSAGE_TEXT" VARCHAR2(500 BYTE), 
	"USEYN" VARCHAR2(2 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;

   COMMENT ON COLUMN "PREMIER"."C_0061"."SYSTEMCD" IS '시스템코드';
   COMMENT ON COLUMN "PREMIER"."C_0061"."CATALOGCD" IS 'Catalog';
   COMMENT ON COLUMN "PREMIER"."C_0061"."LANG" IS '언어';
   COMMENT ON COLUMN "PREMIER"."C_0061"."MESSAGE_TEXT" IS '메세지내용';
   COMMENT ON COLUMN "PREMIER"."C_0061"."USEYN" IS '사용유무';
   COMMENT ON TABLE "PREMIER"."C_0061"  IS 'MESSAGE Catalog 값';
