--------------------------------------------------------
--  DDL for Table C_0051_221116
--------------------------------------------------------

  CREATE TABLE "PREMIER"."C_0051_221116" 
   (	"SYSTEMCD" VARCHAR2(3 BYTE), 
	"CATALOGCD" VARCHAR2(30 BYTE), 
	"LANG" VARCHAR2(10 BYTE), 
	"LISTVALUE" VARCHAR2(60 BYTE), 
	"LISTDESCR" VARCHAR2(500 BYTE), 
	"LISTORDER" NUMBER, 
	"USEYN" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;
