--------------------------------------------------------
--  DDL for Table C_0011_NEW
--------------------------------------------------------

  CREATE TABLE "PREMIER"."C_0011_NEW" 
   (	"COMPANYCD" VARCHAR2(2 BYTE), 
	"GUBUN" VARCHAR2(1 BYTE), 
	"XUSER" VARCHAR2(20 BYTE), 
	"PASS" VARCHAR2(20 BYTE), 
	"PYMD" DATE, 
	"XUSERNM" VARCHAR2(52 BYTE), 
	"USEYN" VARCHAR2(1 BYTE), 
	"TEAMCD" VARCHAR2(6 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"MOBILE" VARCHAR2(100 BYTE), 
	"XUSERNM_ENG" VARCHAR2(100 BYTE), 
	"JIKUP" VARCHAR2(10 BYTE), 
	"C_0010_ID" VARCHAR2(30 BYTE), 
	"LANG" VARCHAR2(2 BYTE), 
	"RANKID" VARCHAR2(20 BYTE), 
	"EFAM_ID" VARCHAR2(50 BYTE), 
	"PASS_FAILURE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;
