--------------------------------------------------------
--  DDL for Table C_0031
--------------------------------------------------------

  CREATE TABLE "PREMIER"."C_0031" 
   (	"SYSTEMCD" VARCHAR2(3 BYTE), 
	"GRADE" VARCHAR2(10 BYTE), 
	"PGMID" VARCHAR2(20 BYTE), 
	"PGM_LEVEL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;

   COMMENT ON COLUMN "PREMIER"."C_0031"."SYSTEMCD" IS '시스템코드';
   COMMENT ON COLUMN "PREMIER"."C_0031"."GRADE" IS '등급';
   COMMENT ON COLUMN "PREMIER"."C_0031"."PGMID" IS '프로그램 ID';
   COMMENT ON COLUMN "PREMIER"."C_0031"."PGM_LEVEL" IS '프로그램등급(10.삭제, 20.편집, 30.출력, 40.출력, 50.조회)';
   COMMENT ON TABLE "PREMIER"."C_0031"  IS '시스템 등급 프로그램목록';
