--------------------------------------------------------
--  DDL for Table C_0051
--------------------------------------------------------

  CREATE TABLE "PREMIER"."C_0051" 
   (	"SYSTEMCD" VARCHAR2(3 BYTE), 
	"CATALOGCD" VARCHAR2(30 BYTE), 
	"LANG" VARCHAR2(10 BYTE), 
	"LISTVALUE" VARCHAR2(60 BYTE), 
	"LISTDESCR" VARCHAR2(500 BYTE), 
	"LISTORDER" NUMBER, 
	"USEYN" VARCHAR2(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;

   COMMENT ON COLUMN "PREMIER"."C_0051"."SYSTEMCD" IS '시스템코드';
   COMMENT ON COLUMN "PREMIER"."C_0051"."CATALOGCD" IS 'Catalog';
   COMMENT ON COLUMN "PREMIER"."C_0051"."LANG" IS '언어';
   COMMENT ON COLUMN "PREMIER"."C_0051"."LISTVALUE" IS '내용코드';
   COMMENT ON COLUMN "PREMIER"."C_0051"."LISTDESCR" IS '내용';
   COMMENT ON COLUMN "PREMIER"."C_0051"."LISTORDER" IS '정렬순서';
   COMMENT ON COLUMN "PREMIER"."C_0051"."USEYN" IS '사용유무';
   COMMENT ON TABLE "PREMIER"."C_0051"  IS 'Catalog 값';
