--------------------------------------------------------
--  DDL for Table C_0040
--------------------------------------------------------

  CREATE TABLE "PREMIER"."C_0040" 
   (	"SYSTEMCD" VARCHAR2(3 BYTE), 
	"PGMID" VARCHAR2(20 BYTE), 
	"DESCR" VARCHAR2(100 BYTE), 
	"USEYN" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"DEVEYMD" VARCHAR2(8 BYTE), 
	"MEMO" VARCHAR2(50 BYTE), 
	"PGM_GB" VARCHAR2(20 BYTE), 
	"ID_" NUMBER, 
	"CONTENT" VARCHAR2(1000 BYTE), 
	"PGM_EXPLAIN" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;

   COMMENT ON COLUMN "PREMIER"."C_0040"."SYSTEMCD" IS '시스템코드';
   COMMENT ON COLUMN "PREMIER"."C_0040"."PGMID" IS '프로그램ID';
   COMMENT ON COLUMN "PREMIER"."C_0040"."DESCR" IS '프로그램명';
   COMMENT ON COLUMN "PREMIER"."C_0040"."USEYN" IS '사용유무';
   COMMENT ON COLUMN "PREMIER"."C_0040"."DEVEYMD" IS '개발일';
   COMMENT ON COLUMN "PREMIER"."C_0040"."MEMO" IS '비고';
   COMMENT ON TABLE "PREMIER"."C_0040"  IS '프로그램 마스타 (자식:C0041)';
