--------------------------------------------------------
--  DDL for Table C_0046
--------------------------------------------------------

  CREATE TABLE "PREMIER"."C_0046" 
   (	"SYSTEMCD" VARCHAR2(3 BYTE), 
	"PGMID" VARCHAR2(10 BYTE), 
	"FIELDCD" VARCHAR2(30 BYTE), 
	"LANG" VARCHAR2(10 BYTE), 
	"FIELDNM" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;

   COMMENT ON COLUMN "PREMIER"."C_0046"."SYSTEMCD" IS '시스템코드';
   COMMENT ON COLUMN "PREMIER"."C_0046"."PGMID" IS '프로그램ID';
   COMMENT ON COLUMN "PREMIER"."C_0046"."FIELDCD" IS '필드변수';
   COMMENT ON COLUMN "PREMIER"."C_0046"."LANG" IS '언어';
   COMMENT ON COLUMN "PREMIER"."C_0046"."FIELDNM" IS '필드변수명';
   COMMENT ON TABLE "PREMIER"."C_0046"  IS '프로그램 필드 마스타';
