--------------------------------------------------------
--  DDL for Table C_2000
--------------------------------------------------------

  CREATE TABLE "PREMIER"."C_2000" 
   (	"KNAME" VARCHAR2(500 BYTE), 
	"LANG" VARCHAR2(2 BYTE), 
	"FNAME1" VARCHAR2(500 BYTE), 
	"FNAME2" VARCHAR2(500 BYTE), 
	"FNAME3" VARCHAR2(500 BYTE), 
	"FNAME4" VARCHAR2(500 BYTE), 
	"FNAME5" VARCHAR2(500 BYTE), 
	"LOGIN_ID" VARCHAR2(20 BYTE), 
	"LOGIN_YMD" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;

   COMMENT ON COLUMN "PREMIER"."C_2000"."KNAME" IS '한글명(띄어쓰기삭제)';
   COMMENT ON COLUMN "PREMIER"."C_2000"."LANG" IS '언어(대문자)';
   COMMENT ON COLUMN "PREMIER"."C_2000"."FNAME1" IS '필드명1';
   COMMENT ON COLUMN "PREMIER"."C_2000"."FNAME2" IS '필드명2';
   COMMENT ON COLUMN "PREMIER"."C_2000"."FNAME3" IS '필드명3';
   COMMENT ON COLUMN "PREMIER"."C_2000"."FNAME4" IS '필드명4';
   COMMENT ON COLUMN "PREMIER"."C_2000"."FNAME5" IS '필드명5';
   COMMENT ON TABLE "PREMIER"."C_2000"  IS '필드명(언어변환)';
