--------------------------------------------------------
--  DDL for Table CM0075T
--------------------------------------------------------

  CREATE TABLE "PREMIER"."CM0075T" 
   (	"COMPANYCD" VARCHAR2(2 BYTE), 
	"VENDCD" VARCHAR2(20 BYTE), 
	"BUSINO" VARCHAR2(50 BYTE), 
	"SDATE" DATE, 
	"LDATE" DATE, 
	"VENDNM" VARCHAR2(150 BYTE), 
	"PRESNM" VARCHAR2(100 BYTE), 
	"IDNO" VARCHAR2(50 BYTE), 
	"BCOND" VARCHAR2(200 BYTE), 
	"BKIND" VARCHAR2(200 BYTE), 
	"ADDRESS" VARCHAR2(300 BYTE), 
	"LOGIN_ID" VARCHAR2(30 BYTE), 
	"LOGIN_YMD" DATE, 
	"ICGBN" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 5 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;

   COMMENT ON COLUMN "PREMIER"."CM0075T"."COMPANYCD" IS '사업장';
   COMMENT ON COLUMN "PREMIER"."CM0075T"."VENDCD" IS '업체코드';
   COMMENT ON COLUMN "PREMIER"."CM0075T"."BUSINO" IS '사업자번호';
   COMMENT ON COLUMN "PREMIER"."CM0075T"."SDATE" IS '거래시작일  (yyyymmdd)';
   COMMENT ON COLUMN "PREMIER"."CM0075T"."LDATE" IS '거래종료일  (yyyymmdd)';
   COMMENT ON COLUMN "PREMIER"."CM0075T"."VENDNM" IS '업체명';
   COMMENT ON COLUMN "PREMIER"."CM0075T"."PRESNM" IS '대표자성명';
   COMMENT ON COLUMN "PREMIER"."CM0075T"."IDNO" IS '주민등록번호';
   COMMENT ON COLUMN "PREMIER"."CM0075T"."BCOND" IS '업태';
   COMMENT ON COLUMN "PREMIER"."CM0075T"."BKIND" IS '업종';
   COMMENT ON COLUMN "PREMIER"."CM0075T"."ADDRESS" IS '주소';
   COMMENT ON COLUMN "PREMIER"."CM0075T"."ICGBN" IS '사업자(C)/개인(I) 구분';
   COMMENT ON TABLE "PREMIER"."CM0075T"  IS '업체 MASTER-사업자번호';
