--------------------------------------------------------
--  DDL for Table CM0070T
--------------------------------------------------------

  CREATE TABLE "PREMIER"."CM0070T" 
   (	"COMPANYCD" VARCHAR2(2 BYTE), 
	"VENDCD" VARCHAR2(20 BYTE), 
	"VENDNM" VARCHAR2(100 BYTE), 
	"CREDATE" DATE, 
	"POSTNO" VARCHAR2(50 BYTE), 
	"ADDRESS" VARCHAR2(300 BYTE), 
	"TELNO" VARCHAR2(50 BYTE), 
	"FAXNO" VARCHAR2(50 BYTE), 
	"COINCD" VARCHAR2(20 BYTE), 
	"HURL" VARCHAR2(50 BYTE), 
	"BANKNM" VARCHAR2(50 BYTE), 
	"ACCNO" VARCHAR2(50 BYTE), 
	"ACCNM" VARCHAR2(50 BYTE), 
	"FORDOMGBN" VARCHAR2(20 BYTE), 
	"USEYN" VARCHAR2(20 BYTE) DEFAULT 'Y', 
	"LOGIN_ID" VARCHAR2(30 BYTE), 
	"LOGIN_YMD" DATE, 
	"C_0010_ID" VARCHAR2(30 BYTE), 
	"PAYGBN_VENDCD" VARCHAR2(20 BYTE), 
	"B2B_COMPANYCD" VARCHAR2(20 BYTE) DEFAULT null, 
	"COUNTRY_CODE" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 5 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 393216 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;

   COMMENT ON COLUMN "PREMIER"."CM0070T"."COMPANYCD" IS '사업장';
   COMMENT ON COLUMN "PREMIER"."CM0070T"."VENDCD" IS '업체코드';
   COMMENT ON COLUMN "PREMIER"."CM0070T"."VENDNM" IS '업체명';
   COMMENT ON COLUMN "PREMIER"."CM0070T"."CREDATE" IS '설립일자';
   COMMENT ON COLUMN "PREMIER"."CM0070T"."POSTNO" IS '우편번호';
   COMMENT ON COLUMN "PREMIER"."CM0070T"."ADDRESS" IS '주소';
   COMMENT ON COLUMN "PREMIER"."CM0070T"."TELNO" IS '전화번호';
   COMMENT ON COLUMN "PREMIER"."CM0070T"."FAXNO" IS 'FAX번호';
   COMMENT ON COLUMN "PREMIER"."CM0070T"."COINCD" IS 'Catalog- 통화코드-구매관련';
   COMMENT ON COLUMN "PREMIER"."CM0070T"."HURL" IS '홈페이지';
   COMMENT ON COLUMN "PREMIER"."CM0070T"."BANKNM" IS '거래은행';
   COMMENT ON COLUMN "PREMIER"."CM0070T"."ACCNO" IS '계좌번호';
   COMMENT ON COLUMN "PREMIER"."CM0070T"."ACCNM" IS '예금주명';
   COMMENT ON COLUMN "PREMIER"."CM0070T"."FORDOMGBN" IS '지역(1.국내 2.해외)';
   COMMENT ON COLUMN "PREMIER"."CM0070T"."USEYN" IS '사용유무';
   COMMENT ON COLUMN "PREMIER"."CM0070T"."C_0010_ID" IS '로그인-ID (Companycd-Vendcd)';
   COMMENT ON COLUMN "PREMIER"."CM0070T"."PAYGBN_VENDCD" IS '물품대 지급 기준';
   COMMENT ON COLUMN "PREMIER"."CM0070T"."B2B_COMPANYCD" IS '계열사구분';
   COMMENT ON COLUMN "PREMIER"."CM0070T"."COUNTRY_CODE" IS '국가코드';
   COMMENT ON TABLE "PREMIER"."CM0070T"  IS '업체 MASTER';
