--------------------------------------------------------
--  DDL for Table CM0077T
--------------------------------------------------------

  CREATE TABLE "PREMIER"."CM0077T" 
   (	"COMPANYCD" VARCHAR2(2 BYTE), 
	"VENDCD" VARCHAR2(20 BYTE), 
	"SNO" NUMBER, 
	"DEPTNM" VARCHAR2(50 BYTE), 
	"EMPNM" VARCHAR2(50 BYTE), 
	"TELNO" VARCHAR2(50 BYTE), 
	"BPNO" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"MEMO" VARCHAR2(200 BYTE), 
	"LOGIN_ID" VARCHAR2(30 BYTE), 
	"LOGIN_YMD" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 5 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 524288 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;

   COMMENT ON COLUMN "PREMIER"."CM0077T"."COMPANYCD" IS '사업장';
   COMMENT ON COLUMN "PREMIER"."CM0077T"."VENDCD" IS '업체코드';
   COMMENT ON COLUMN "PREMIER"."CM0077T"."SNO" IS '순번';
   COMMENT ON COLUMN "PREMIER"."CM0077T"."DEPTNM" IS '부서명';
   COMMENT ON COLUMN "PREMIER"."CM0077T"."EMPNM" IS '담당자';
   COMMENT ON COLUMN "PREMIER"."CM0077T"."TELNO" IS '전화번호';
   COMMENT ON COLUMN "PREMIER"."CM0077T"."BPNO" IS '핸드폰';
   COMMENT ON COLUMN "PREMIER"."CM0077T"."EMAIL" IS '메일';
   COMMENT ON COLUMN "PREMIER"."CM0077T"."MEMO" IS '비고';
   COMMENT ON TABLE "PREMIER"."CM0077T"  IS '거래처-담당자정보';
