--------------------------------------------------------
--  DDL for Table CM0060T
--------------------------------------------------------

  CREATE TABLE "PREMIER"."CM0060T" 
   (	"COMPANYCD" VARCHAR2(2 BYTE), 
	"LINECD" VARCHAR2(20 BYTE), 
	"SYMD" VARCHAR2(8 BYTE), 
	"BYMD" VARCHAR2(8 BYTE), 
	"LINENM" VARCHAR2(100 BYTE), 
	"LINEGBN" VARCHAR2(2 BYTE), 
	"LINEDIRECTGBN" VARCHAR2(2 BYTE), 
	"LINETYPEGBN" VARCHAR2(2 BYTE), 
	"LINEWONGAGBN" VARCHAR2(2 BYTE), 
	"LINEDNGBN" VARCHAR2(2 BYTE), 
	"LINELOCALGBN" VARCHAR2(2 BYTE) DEFAULT '10', 
	"T_MAN" NUMBER DEFAULT 0, 
	"T_WOMAN" NUMBER DEFAULT 0, 
	"T_COMPANYCD" VARCHAR2(2 BYTE), 
	"T_XUSER" VARCHAR2(20 BYTE), 
	"LOGIN_ID" VARCHAR2(30 BYTE), 
	"LOGIN_YMD" DATE, 
	"PUMCD" VARCHAR2(20 BYTE), 
	"WONGBN" VARCHAR2(1 BYTE), 
	"YESANGBN" VARCHAR2(1 BYTE), 
	"MONITOR_YN" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"TO_INWON" NUMBER, 
	"B_GBN" VARCHAR2(20 BYTE), 
	"LISTORDER" NUMBER, 
	"QIS_1" VARCHAR2(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 5 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;

   COMMENT ON COLUMN "PREMIER"."CM0060T"."COMPANYCD" IS '사업장';
   COMMENT ON COLUMN "PREMIER"."CM0060T"."LINECD" IS '라인코드';
   COMMENT ON COLUMN "PREMIER"."CM0060T"."SYMD" IS '적용일자';
   COMMENT ON COLUMN "PREMIER"."CM0060T"."BYMD" IS '종료일자';
   COMMENT ON COLUMN "PREMIER"."CM0060T"."LINENM" IS '라인명';
   COMMENT ON COLUMN "PREMIER"."CM0060T"."LINEGBN" IS 'Catalog- 부서구분(10.공장, 20.부문, 30.팀, 40.파트 50.반 60.조 70.라인) ';
   COMMENT ON COLUMN "PREMIER"."CM0060T"."LINEDIRECTGBN" IS 'Catalog- 직간접구분(10.직접 20.간접)';
   COMMENT ON COLUMN "PREMIER"."CM0060T"."LINETYPEGBN" IS 'Catalog- 라인형태구분(10.ASSY 20.SUB 30.PRESS 40.ETC)';
   COMMENT ON COLUMN "PREMIER"."CM0060T"."LINEWONGAGBN" IS 'Catalog- 라인원가구분(10.일반관리비 20.노무비)';
   COMMENT ON COLUMN "PREMIER"."CM0060T"."LINEDNGBN" IS 'Catalog- 라인근무구분(10.주간 20.2교대 30.3교대)';
   COMMENT ON COLUMN "PREMIER"."CM0060T"."LINELOCALGBN" IS 'Catalog- 구분(10.국내 20.해외)';
   COMMENT ON COLUMN "PREMIER"."CM0060T"."T_MAN" IS '현재원(남)';
   COMMENT ON COLUMN "PREMIER"."CM0060T"."T_WOMAN" IS '현재원(여)';
   COMMENT ON COLUMN "PREMIER"."CM0060T"."T_COMPANYCD" IS '책임자사업장';
   COMMENT ON COLUMN "PREMIER"."CM0060T"."T_XUSER" IS '책임자사번';
   COMMENT ON COLUMN "PREMIER"."CM0060T"."PUMCD" IS 'Catalog-품목';
   COMMENT ON COLUMN "PREMIER"."CM0060T"."WONGBN" IS '원가관리부서';
   COMMENT ON COLUMN "PREMIER"."CM0060T"."YESANGBN" IS '예산관리부서';
   COMMENT ON COLUMN "PREMIER"."CM0060T"."MONITOR_YN" IS '모니터구분(Y/N)';
   COMMENT ON COLUMN "PREMIER"."CM0060T"."TO_INWON" IS 'TO인원';
   COMMENT ON COLUMN "PREMIER"."CM0060T"."B_GBN" IS '광진상공-공장별도구분';
   COMMENT ON COLUMN "PREMIER"."CM0060T"."LISTORDER" IS '정렬순서';
   COMMENT ON TABLE "PREMIER"."CM0060T"  IS '부서코드 MASTER';
