--------------------------------------------------------
--  DDL for Table CM0079T
--------------------------------------------------------

  CREATE TABLE "PREMIER"."CM0079T" 
   (	"COMPANYCD" VARCHAR2(2 BYTE), 
	"TIMEZONE" VARCHAR2(2 BYTE), 
	"SYMD" DATE, 
	"EYMD" DATE, 
	"REMARK" VARCHAR2(100 BYTE), 
	"LOGIN_ID" VARCHAR2(30 BYTE), 
	"LOGIN_YMD" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 40 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;

   COMMENT ON COLUMN "PREMIER"."CM0079T"."COMPANYCD" IS '사업장';
   COMMENT ON COLUMN "PREMIER"."CM0079T"."TIMEZONE" IS 'TIMEZONE 구분(ET/ED)';
   COMMENT ON COLUMN "PREMIER"."CM0079T"."SYMD" IS '시작일';
   COMMENT ON COLUMN "PREMIER"."CM0079T"."EYMD" IS '종료일';
   COMMENT ON COLUMN "PREMIER"."CM0079T"."REMARK" IS '비고';
   COMMENT ON TABLE "PREMIER"."CM0079T"  IS 'TIME ZONE 구분';
