--------------------------------------------------------
--  DDL for Table EXAM_USER_LIST
--------------------------------------------------------

  CREATE TABLE "PREMIER"."EXAM_USER_LIST" 
   (	"COMPANYCD" VARCHAR2(2 BYTE), 
	"XUSER" VARCHAR2(20 BYTE), 
	"AREA_IP" VARCHAR2(20 BYTE), 
	"PC_IP" VARCHAR2(20 BYTE), 
	"PC_NAME" VARCHAR2(200 BYTE), 
	"CONNECT_DATE" DATE, 
	"TEST_START" VARCHAR2(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;

   COMMENT ON COLUMN "PREMIER"."EXAM_USER_LIST"."COMPANYCD" IS '사업장';
   COMMENT ON COLUMN "PREMIER"."EXAM_USER_LIST"."XUSER" IS '로긴ID';
   COMMENT ON COLUMN "PREMIER"."EXAM_USER_LIST"."AREA_IP" IS '외부IP';
   COMMENT ON COLUMN "PREMIER"."EXAM_USER_LIST"."PC_IP" IS '내부 PC IP';
   COMMENT ON COLUMN "PREMIER"."EXAM_USER_LIST"."PC_NAME" IS '내부 컴퓨터명';
   COMMENT ON COLUMN "PREMIER"."EXAM_USER_LIST"."CONNECT_DATE" IS '접속시간';
   COMMENT ON TABLE "PREMIER"."EXAM_USER_LIST"  IS '로그인 마스타';
