--------------------------------------------------------
--  DDL for Table G_600
--------------------------------------------------------

  CREATE TABLE "PREMIER"."G_600" 
   (	"YY" VARCHAR2(4 BYTE), 
	"G_GBN" VARCHAR2(1 BYTE), 
	"G_COMPANYCD" VARCHAR2(2 BYTE), 
	"G_CODE" VARCHAR2(2 BYTE), 
	"COMPANYCD" VARCHAR2(2 BYTE), 
	"GUBUN" VARCHAR2(1 BYTE), 
	"XUSER" VARCHAR2(20 BYTE), 
	"SNO" NUMBER DEFAULT 0, 
	"TITLE" VARCHAR2(53 BYTE), 
	"VENDNM" VARCHAR2(55 BYTE), 
	"DESCR" VARCHAR2(4000 BYTE), 
	"DYMD" DATE DEFAULT sysdate, 
	"PYMD" VARCHAR2(8 BYTE), 
	"YYMD" VARCHAR2(8 BYTE), 
	"TEAMCD" VARCHAR2(20 BYTE), 
	"DSYN" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"SECLEVEL" VARCHAR2(10 BYTE), 
	"LOGIN_COMPANYCD" VARCHAR2(2 BYTE), 
	"LOGIN_ID" VARCHAR2(20 BYTE), 
	"LOGIN_YMD" DATE, 
	"KINDCD" VARCHAR2(100 BYTE), 
	"PAMT" NUMBER DEFAULT 0, 
	"YAMT" NUMBER DEFAULT 0, 
	"EO_NO" VARCHAR2(1024 BYTE), 
	"APNO" VARCHAR2(50 BYTE), 
	"REF_KEY" VARCHAR2(100 BYTE), 
	"WONGA_GBN" VARCHAR2(2 BYTE), 
	"APPLY_COMPANYCD" VARCHAR2(2 BYTE), 
	"CSNO" VARCHAR2(50 BYTE), 
	"DOC_TITLE" VARCHAR2(2000 BYTE), 
	"REPORT_DESCR" CLOB, 
	"MBO_CONFIRM" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"JUNKUL" VARCHAR2(20 BYTE), 
	"REF_KEY_NUMBER" NUMBER, 
	"PGMID" VARCHAR2(20 BYTE), 
	"FAMT" NUMBER DEFAULT 0, 
	"INVEST_TYPE" VARCHAR2(20 BYTE), 
	"WORK_HOME" VARCHAR2(10 BYTE), 
	"DOC_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 40 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 7340032 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" 
 LOB ("REPORT_DESCR") STORE AS SECUREFILE (
  TABLESPACE "PREMIER_DAT" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "PREMIER"."G_600"."YY" IS '년도';
   COMMENT ON COLUMN "PREMIER"."G_600"."G_GBN" IS 'G_601 Table';
   COMMENT ON COLUMN "PREMIER"."G_600"."G_COMPANYCD" IS 'G_601';
   COMMENT ON COLUMN "PREMIER"."G_600"."G_CODE" IS 'G_601';
   COMMENT ON COLUMN "PREMIER"."G_600"."COMPANYCD" IS 'C_0010 Table';
   COMMENT ON COLUMN "PREMIER"."G_600"."GUBUN" IS 'C_0010';
   COMMENT ON COLUMN "PREMIER"."G_600"."XUSER" IS 'C_0010';
   COMMENT ON COLUMN "PREMIER"."G_600"."SNO" IS '순번';
   COMMENT ON COLUMN "PREMIER"."G_600"."TITLE" IS '분류항목';
   COMMENT ON COLUMN "PREMIER"."G_600"."VENDNM" IS '관련업체';
   COMMENT ON COLUMN "PREMIER"."G_600"."DESCR" IS '내용';
   COMMENT ON COLUMN "PREMIER"."G_600"."DYMD" IS '업무일지등록일, 회의일자, 주요업무계획일, 회의일자, 제안심사요구일';
   COMMENT ON COLUMN "PREMIER"."G_600"."PYMD" IS '계획일';
   COMMENT ON COLUMN "PREMIER"."G_600"."YYMD" IS '완료일';
   COMMENT ON COLUMN "PREMIER"."G_600"."TEAMCD" IS '팀코드';
   COMMENT ON COLUMN "PREMIER"."G_600"."DSYN" IS '대상여부(Y/N)';
   COMMENT ON COLUMN "PREMIER"."G_600"."SECLEVEL" IS '보안레벨';
   COMMENT ON COLUMN "PREMIER"."G_600"."KINDCD" IS '차종';
   COMMENT ON COLUMN "PREMIER"."G_600"."PAMT" IS '예상금액';
   COMMENT ON COLUMN "PREMIER"."G_600"."YAMT" IS '완료금액(발생비용)';
   COMMENT ON COLUMN "PREMIER"."G_600"."EO_NO" IS 'EO번호';
   COMMENT ON COLUMN "PREMIER"."G_600"."APNO" IS '품번';
   COMMENT ON COLUMN "PREMIER"."G_600"."REF_KEY" IS '참고키. EO회의일 경우 companycd(2)+dymd(14)+eo관련항목(4)';
   COMMENT ON COLUMN "PREMIER"."G_600"."WONGA_GBN" IS 'Catalog- 원가절감구분';
   COMMENT ON COLUMN "PREMIER"."G_600"."APPLY_COMPANYCD" IS '적용사업장';
   COMMENT ON COLUMN "PREMIER"."G_600"."FAMT" IS '실패비용';
   COMMENT ON COLUMN "PREMIER"."G_600"."INVEST_TYPE" IS '투자비구분';
   COMMENT ON COLUMN "PREMIER"."G_600"."WORK_HOME" IS '재택근무여부';
   COMMENT ON COLUMN "PREMIER"."G_600"."DOC_ID" IS '재택근무일때만 결재 사용';
   COMMENT ON TABLE "PREMIER"."G_600"  IS '업무일지,주요업무,회의록';
