--------------------------------------------------------
--  DDL for Table LOGIN_ADDRESS
--------------------------------------------------------

  CREATE TABLE "PREMIER"."LOGIN_ADDRESS" 
   (	"LOGIN_ID" VARCHAR2(20 BYTE), 
	"LOGIN_COMPANYCD" VARCHAR2(2 BYTE), 
	"LOGIN_YMD" DATE, 
	"IP" VARCHAR2(100 BYTE), 
	"IP2" VARCHAR2(100 BYTE), 
	"LOGIN_YN" VARCHAR2(20 BYTE), 
	"TERMINAL" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 40 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;

   COMMENT ON COLUMN "PREMIER"."LOGIN_ADDRESS"."LOGIN_YN" IS '로그인정보';
