--------------------------------------------------------
--  DDL for Table MASTER_LANGUAGE
--------------------------------------------------------

  CREATE TABLE "PREMIER"."MASTER_LANGUAGE" 
   (	"TABLEID" VARCHAR2(100 BYTE), 
	"COMPANYCD" VARCHAR2(2 BYTE), 
	"CODE" VARCHAR2(100 BYTE), 
	"GUBUN" VARCHAR2(1 BYTE), 
	"LANG" VARCHAR2(10 BYTE), 
	"NAME" VARCHAR2(1024 BYTE), 
	"LOGINCOMP" VARCHAR2(2 BYTE), 
	"LOGINID" VARCHAR2(20 BYTE), 
	"LOGINYMD" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;
