--------------------------------------------------------
--  DDL for Table MM4035T
--------------------------------------------------------

  CREATE TABLE "PREMIER"."MM4035T" 
   (	"COMPANYCD" VARCHAR2(2 BYTE), 
	"VENDCD" VARCHAR2(20 BYTE), 
	"APNO" VARCHAR2(50 BYTE), 
	"GROUPCD" VARCHAR2(20 BYTE), 
	"LIST_ORDER" NUMBER, 
	"LOGIN_ID" VARCHAR2(30 BYTE), 
	"LOGIN_YMD" DATE, 
	"S_VENDCD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 5 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;

   COMMENT ON COLUMN "PREMIER"."MM4035T"."COMPANYCD" IS '사업장';
   COMMENT ON COLUMN "PREMIER"."MM4035T"."VENDCD" IS '거래처코드';
   COMMENT ON COLUMN "PREMIER"."MM4035T"."APNO" IS '품번';
   COMMENT ON COLUMN "PREMIER"."MM4035T"."GROUPCD" IS '그룹코드';
   COMMENT ON COLUMN "PREMIER"."MM4035T"."LIST_ORDER" IS '순서';
   COMMENT ON COLUMN "PREMIER"."MM4035T"."S_VENDCD" IS '공급 협력업체';
   COMMENT ON TABLE "PREMIER"."MM4035T"  IS '사급품정보마스타';
