--------------------------------------------------------
--  DDL for Table MM4030T
--------------------------------------------------------

  CREATE TABLE "PREMIER"."MM4030T" 
   (	"COMPANYCD" VARCHAR2(2 BYTE), 
	"VENDCD" VARCHAR2(20 BYTE), 
	"GROUPCD" VARCHAR2(20 BYTE), 
	"DESCR" VARCHAR2(200 BYTE), 
	"LIST_ORDER" NUMBER, 
	"LOGIN_ID" VARCHAR2(30 BYTE), 
	"LOGIN_YMD" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 5 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;

   COMMENT ON COLUMN "PREMIER"."MM4030T"."COMPANYCD" IS '사업장';
   COMMENT ON COLUMN "PREMIER"."MM4030T"."VENDCD" IS '거래처코드';
   COMMENT ON COLUMN "PREMIER"."MM4030T"."GROUPCD" IS '그룹코드';
   COMMENT ON COLUMN "PREMIER"."MM4030T"."DESCR" IS '명칭';
   COMMENT ON COLUMN "PREMIER"."MM4030T"."LIST_ORDER" IS '순번';
   COMMENT ON TABLE "PREMIER"."MM4030T"  IS '사급품정보-그룹코드';
