--------------------------------------------------------
--  DDL for Table Q_705
--------------------------------------------------------

  CREATE TABLE "PREMIER"."Q_705" 
   (	"COMPANYCD" VARCHAR2(2 BYTE), 
	"GUBUN" VARCHAR2(20 BYTE), 
	"LANG" VARCHAR2(10 BYTE), 
	"SNO" NUMBER, 
	"DEPT" VARCHAR2(200 BYTE), 
	"LISTDESCR" VARCHAR2(400 BYTE), 
	"LOGIN_COMPANYCD" VARCHAR2(2 BYTE), 
	"LOGIN_ID" VARCHAR2(20 BYTE), 
	"LOGIN_YMD" DATE, 
	"SEQ" NUMBER, 
	"FINISH_FLAG" VARCHAR2(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 30 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;

   COMMENT ON COLUMN "PREMIER"."Q_705"."COMPANYCD" IS '사업장';
   COMMENT ON COLUMN "PREMIER"."Q_705"."GUBUN" IS '내역구분';
   COMMENT ON COLUMN "PREMIER"."Q_705"."LANG" IS '언어(KO,EN)';
   COMMENT ON COLUMN "PREMIER"."Q_705"."SNO" IS '순번';
   COMMENT ON COLUMN "PREMIER"."Q_705"."DEPT" IS '부서';
   COMMENT ON COLUMN "PREMIER"."Q_705"."LISTDESCR" IS '내용';
   COMMENT ON COLUMN "PREMIER"."Q_705"."LOGIN_COMPANYCD" IS '로그인-사업장';
   COMMENT ON COLUMN "PREMIER"."Q_705"."LOGIN_ID" IS '로그인-ID';
   COMMENT ON COLUMN "PREMIER"."Q_705"."LOGIN_YMD" IS '로그인-일자';
   COMMENT ON TABLE "PREMIER"."Q_705"  IS '개발타당성검토서내역';
