--------------------------------------------------------
--  DDL for Table QIS_UPLOAD_FILE
--------------------------------------------------------

  CREATE TABLE "PREMIER"."QIS_UPLOAD_FILE" 
   (	"NAME" VARCHAR2(501 BYTE), 
	"MIME_TYPE" VARCHAR2(128 BYTE), 
	"DOC_SIZE" NUMBER, 
	"DAD_CHARSET" VARCHAR2(128 BYTE), 
	"LAST_UPDATED" DATE, 
	"CONTENT_TYPE" VARCHAR2(128 BYTE), 
	"BLOB_CONTENT" BLOB, 
	"FILE_NAME" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" 
 LOB ("BLOB_CONTENT") STORE AS SECUREFILE (
  TABLESPACE "PREMIER_DOC" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "PREMIER"."QIS_UPLOAD_FILE"."NAME" IS 'FILE명(경로포함)';
   COMMENT ON COLUMN "PREMIER"."QIS_UPLOAD_FILE"."MIME_TYPE" IS 'MIME-TYPE';
   COMMENT ON COLUMN "PREMIER"."QIS_UPLOAD_FILE"."DOC_SIZE" IS 'FILE SIZE';
   COMMENT ON COLUMN "PREMIER"."QIS_UPLOAD_FILE"."DAD_CHARSET" IS 'NLS_CHARSET';
   COMMENT ON COLUMN "PREMIER"."QIS_UPLOAD_FILE"."LAST_UPDATED" IS '최종수정일';
   COMMENT ON COLUMN "PREMIER"."QIS_UPLOAD_FILE"."CONTENT_TYPE" IS 'CONTENT TYPE';
   COMMENT ON COLUMN "PREMIER"."QIS_UPLOAD_FILE"."BLOB_CONTENT" IS 'BLOB_CONTENT';
   COMMENT ON COLUMN "PREMIER"."QIS_UPLOAD_FILE"."FILE_NAME" IS 'FILE명';
   COMMENT ON TABLE "PREMIER"."QIS_UPLOAD_FILE"  IS '품질정보첨부파일TABLE';
