--------------------------------------------------------
--  DDL for Table S_2100
--------------------------------------------------------

  CREATE TABLE "PREMIER"."S_2100" 
   (	"COMPANYCD" VARCHAR2(2 BYTE), 
	"VENDCD" VARCHAR2(20 BYTE), 
	"YMD" DATE, 
	"CAPNO" VARCHAR2(50 BYTE), 
	"QTY" NUMBER, 
	"DESCR" VARCHAR2(100 BYTE), 
	"LOGIN_ID" VARCHAR2(30 BYTE), 
	"LOGIN_YMD" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 5 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;

   COMMENT ON COLUMN "PREMIER"."S_2100"."COMPANYCD" IS '사업장';
   COMMENT ON COLUMN "PREMIER"."S_2100"."VENDCD" IS '물류업체';
   COMMENT ON COLUMN "PREMIER"."S_2100"."YMD" IS '재고기준일자';
   COMMENT ON COLUMN "PREMIER"."S_2100"."CAPNO" IS '품번';
   COMMENT ON COLUMN "PREMIER"."S_2100"."QTY" IS '수량';
   COMMENT ON COLUMN "PREMIER"."S_2100"."DESCR" IS '비고';
   COMMENT ON TABLE "PREMIER"."S_2100"  IS '물류업체 재고 등록';
