--------------------------------------------------------
--  DDL for Table S_2500
--------------------------------------------------------

  CREATE TABLE "PREMIER"."S_2500" 
   (	"COMPANYCD" VARCHAR2(2 BYTE), 
	"VENDCD" VARCHAR2(20 BYTE), 
	"SVENDCD" VARCHAR2(20 BYTE), 
	"SAUP" VARCHAR2(20 BYTE), 
	"SYMD" DATE, 
	"PONO" VARCHAR2(100 BYTE), 
	"LOGIN_ID" VARCHAR2(30 BYTE), 
	"LOGIN_YMD" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 5 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;
