--------------------------------------------------------
--  DDL for Table TEMP_LJS
--------------------------------------------------------

  CREATE TABLE "PREMIER"."TEMP_LJS" 
   (	"COMPANYCD" VARCHAR2(2 BYTE), 
	"REGISTER_NO" VARCHAR2(100 BYTE), 
	"LOGIN_COMPANYCD" VARCHAR2(2 BYTE), 
	"LOGIN_ID" VARCHAR2(20 BYTE), 
	"LOGIN_YMD" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 30 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;

   COMMENT ON COLUMN "PREMIER"."TEMP_LJS"."COMPANYCD" IS '사업장';
   COMMENT ON COLUMN "PREMIER"."TEMP_LJS"."REGISTER_NO" IS '등록번호';
   COMMENT ON TABLE "PREMIER"."TEMP_LJS"  IS '테스트 테이블 LJS';
