--------------------------------------------------------
--  DDL for Table XM000
--------------------------------------------------------

  CREATE TABLE "PREMIER"."XM000" 
   (	"COMPANYCD" VARCHAR2(2 BYTE), 
	"KINDCD" VARCHAR2(20 BYTE), 
	"KINDNM" VARCHAR2(50 BYTE), 
	"DESCR" VARCHAR2(50 BYTE), 
	"VENDCD" VARCHAR2(20 BYTE), 
	"NEWCAR" VARCHAR2(20 BYTE) DEFAULT 'N', 
	"YMD" DATE, 
	"CUSTOMER" VARCHAR2(20 BYTE), 
	"CSNO_A" VARCHAR2(50 BYTE), 
	"CSNO_B" VARCHAR2(50 BYTE), 
	"PRO_COMPANYCD" VARCHAR2(2 BYTE), 
	"DRAW_YN" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"DESIGN_LAB" VARCHAR2(2 BYTE), 
	"DESIGN_LAB2" VARCHAR2(2 BYTE), 
	"PLANT" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 30 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;

   COMMENT ON COLUMN "PREMIER"."XM000"."COMPANYCD" IS '사업장';
   COMMENT ON COLUMN "PREMIER"."XM000"."KINDCD" IS '차종코드';
   COMMENT ON COLUMN "PREMIER"."XM000"."KINDNM" IS '차종명';
   COMMENT ON COLUMN "PREMIER"."XM000"."DESCR" IS '상세';
   COMMENT ON COLUMN "PREMIER"."XM000"."VENDCD" IS '거래업체';
   COMMENT ON COLUMN "PREMIER"."XM000"."NEWCAR" IS '신차여부(Y.N)';
   COMMENT ON COLUMN "PREMIER"."XM000"."YMD" IS '양산일';
   COMMENT ON COLUMN "PREMIER"."XM000"."CUSTOMER" IS 'Catalog-고객처';
   COMMENT ON COLUMN "PREMIER"."XM000"."CSNO_A" IS 'PMS 프로젝트 번호 (APQP)';
   COMMENT ON COLUMN "PREMIER"."XM000"."CSNO_B" IS 'PMS 프로젝트 번호 (개발일정계획)';
   COMMENT ON COLUMN "PREMIER"."XM000"."PRO_COMPANYCD" IS '양산사업장';
   COMMENT ON COLUMN "PREMIER"."XM000"."DESIGN_LAB" IS '설계담당연구소';
   COMMENT ON COLUMN "PREMIER"."XM000"."DESIGN_LAB2" IS '개발담당연구소';
   COMMENT ON COLUMN "PREMIER"."XM000"."PLANT" IS '생산공장';
   COMMENT ON TABLE "PREMIER"."XM000"  IS 'QIS 차종 마스타';
