--------------------------------------------------------
--  DDL for Table XM001
--------------------------------------------------------

  CREATE TABLE "PREMIER"."XM001" 
   (	"COMPANYCD" VARCHAR2(2 BYTE), 
	"DESCR" VARCHAR2(50 BYTE), 
	"PRESNM" VARCHAR2(30 BYTE), 
	"BUSINO" VARCHAR2(20 BYTE), 
	"USEYN" CHAR(1 BYTE), 
	"VENDCD" VARCHAR2(20 BYTE), 
	"SAUP" VARCHAR2(20 BYTE), 
	"DESCR1" VARCHAR2(50 BYTE), 
	"WAREGBN" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"QISGBN" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"DESCR2" VARCHAR2(20 BYTE), 
	"GMSGBN" NVARCHAR2(1) DEFAULT 'N', 
	"PDAGBN" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"ERPGBN" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"CURRENCY_NAME" VARCHAR2(30 BYTE), 
	"COMP_TIME_ZONE" NUMBER, 
	"FOREIGN_YN" VARCHAR2(1 BYTE), 
	"NICK" VARCHAR2(50 BYTE), 
	"CASH_FLOW_ORDER" NUMBER, 
	"KPI_ORDER" NUMBER, 
	"AUDIT_ORDER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 30 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;

   COMMENT ON COLUMN "PREMIER"."XM001"."COMPANYCD" IS '사업장';
   COMMENT ON COLUMN "PREMIER"."XM001"."DESCR" IS '사업장명(Local)';
   COMMENT ON COLUMN "PREMIER"."XM001"."PRESNM" IS '대표자';
   COMMENT ON COLUMN "PREMIER"."XM001"."BUSINO" IS '사업자번호';
   COMMENT ON COLUMN "PREMIER"."XM001"."USEYN" IS '사용유무';
   COMMENT ON COLUMN "PREMIER"."XM001"."VENDCD" IS '업체코드';
   COMMENT ON COLUMN "PREMIER"."XM001"."SAUP" IS '사업장코드';
   COMMENT ON COLUMN "PREMIER"."XM001"."DESCR1" IS '사업장명(공용)';
   COMMENT ON COLUMN "PREMIER"."XM001"."WAREGBN" IS '창고사업장 구분(Y)';
   COMMENT ON COLUMN "PREMIER"."XM001"."QISGBN" IS '품질시스템사용여부';
   COMMENT ON COLUMN "PREMIER"."XM001"."DESCR2" IS '사업장약자';
   COMMENT ON COLUMN "PREMIER"."XM001"."GMSGBN" IS 'GMS시스템사용여부';
   COMMENT ON COLUMN "PREMIER"."XM001"."ERPGBN" IS 'ERP시스템사용여부';
   COMMENT ON COLUMN "PREMIER"."XM001"."CURRENCY_NAME" IS '통화명';
   COMMENT ON COLUMN "PREMIER"."XM001"."COMP_TIME_ZONE" IS 'TIME ZONE';
   COMMENT ON COLUMN "PREMIER"."XM001"."FOREIGN_YN" IS '국내/외사업장구분';
   COMMENT ON COLUMN "PREMIER"."XM001"."NICK" IS '공장별칭';
   COMMENT ON COLUMN "PREMIER"."XM001"."CASH_FLOW_ORDER" IS '주간자금수지현황 대상 사업장 표시 순서';
   COMMENT ON COLUMN "PREMIER"."XM001"."KPI_ORDER" IS 'KPI 사업장 정렬 순서';
   COMMENT ON TABLE "PREMIER"."XM001"  IS '사업장 마스타';
