--------------------------------------------------------
--  DDL for Table XM001_LOGIN
--------------------------------------------------------

  CREATE TABLE "PREMIER"."XM001_LOGIN" 
   (	"COMPANYCD" VARCHAR2(2 BYTE), 
	"DESCR" VARCHAR2(50 BYTE), 
	"PRESNM" VARCHAR2(30 BYTE), 
	"BUSINO" VARCHAR2(20 BYTE), 
	"USEYN" CHAR(1 BYTE), 
	"VENDCD" VARCHAR2(20 BYTE), 
	"SAUP" VARCHAR2(20 BYTE), 
	"DESCR1" VARCHAR2(50 BYTE), 
	"WAREGBN" VARCHAR2(1 BYTE), 
	"QISGBN" VARCHAR2(1 BYTE), 
	"DESCR2" VARCHAR2(20 BYTE), 
	"GMSGBN" NVARCHAR2(1), 
	"PDAGBN" VARCHAR2(1 BYTE), 
	"ERPGBN" VARCHAR2(1 BYTE), 
	"CURRENCY_NAME" VARCHAR2(30 BYTE), 
	"COMP_TIME_ZONE" NUMBER, 
	"FOREIGN_YN" VARCHAR2(1 BYTE), 
	"NICK" VARCHAR2(50 BYTE), 
	"CASH_FLOW_ORDER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;
