--------------------------------------------------------
--  DDL for Table XM000_REGI
--------------------------------------------------------

  CREATE TABLE "PREMIER"."XM000_REGI" 
   (	"COMPANYCD" VARCHAR2(2 BYTE), 
	"KINDCD" VARCHAR2(20 BYTE), 
	"DESCR" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 30 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;

   COMMENT ON COLUMN "PREMIER"."XM000_REGI"."COMPANYCD" IS '사업장';
   COMMENT ON COLUMN "PREMIER"."XM000_REGI"."KINDCD" IS '차종코드';
   COMMENT ON COLUMN "PREMIER"."XM000_REGI"."DESCR" IS '비고';
   COMMENT ON TABLE "PREMIER"."XM000_REGI"  IS 'QIS 차종_등록가능사업장';
