--------------------------------------------------------
--  DDL for Table XM010
--------------------------------------------------------

  CREATE TABLE "PREMIER"."XM010" 
   (	"COMPANYCD" VARCHAR2(2 BYTE), 
	"APNO" VARCHAR2(30 BYTE), 
	"APNONM" VARCHAR2(100 BYTE), 
	"KINDCD" VARCHAR2(30 BYTE), 
	"MATERCD" VARCHAR2(30 BYTE), 
	"APNOGBN" VARCHAR2(20 BYTE), 
	"ITEM" VARCHAR2(30 BYTE), 
	"ATTR1" VARCHAR2(20 BYTE), 
	"ATTR2" VARCHAR2(20 BYTE), 
	"DESCR" VARCHAR2(50 BYTE), 
	"USEYN" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"MATERIAL_CODE" VARCHAR2(20 BYTE), 
	"LOGIN_ID" VARCHAR2(20 BYTE), 
	"LOGIN_YMD" DATE, 
	"LOGIN_COMP" VARCHAR2(2 BYTE), 
	"CALC_QTY" NUMBER DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 30 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 3145728 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;

   COMMENT ON COLUMN "PREMIER"."XM010"."COMPANYCD" IS '사업장';
   COMMENT ON COLUMN "PREMIER"."XM010"."APNO" IS '품번';
   COMMENT ON COLUMN "PREMIER"."XM010"."APNONM" IS '품명';
   COMMENT ON COLUMN "PREMIER"."XM010"."KINDCD" IS '대표차종';
   COMMENT ON COLUMN "PREMIER"."XM010"."MATERCD" IS '재질';
   COMMENT ON COLUMN "PREMIER"."XM010"."APNOGBN" IS '구분';
   COMMENT ON COLUMN "PREMIER"."XM010"."ITEM" IS '고객품번';
   COMMENT ON COLUMN "PREMIER"."XM010"."DESCR" IS '비고';
   COMMENT ON COLUMN "PREMIER"."XM010"."USEYN" IS '사용여부';
   COMMENT ON TABLE "PREMIER"."XM010"  IS '품목 마스터';
