--------------------------------------------------------
--  DDL for Table XM604
--------------------------------------------------------

  CREATE TABLE "PREMIER"."XM604" 
   (	"COMPANYCD" VARCHAR2(2 BYTE), 
	"XUSER" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 40 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;

   COMMENT ON COLUMN "PREMIER"."XM604"."COMPANYCD" IS '사업장';
   COMMENT ON COLUMN "PREMIER"."XM604"."XUSER" IS '권한자';
   COMMENT ON TABLE "PREMIER"."XM604"  IS '팀명권한자';
