--------------------------------------------------------
--  DDL for Table XM606
--------------------------------------------------------

  CREATE TABLE "PREMIER"."XM606" 
   (	"COMPANYCD" VARCHAR2(2 BYTE), 
	"TEAMCD" VARCHAR2(20 BYTE), 
	"SDATE" DATE, 
	"EDATE" DATE, 
	"SORT_" NUMBER DEFAULT 0, 
	"U_TEAMCD" VARCHAR2(20 BYTE), 
	"XUSER_COMP" VARCHAR2(2 BYTE), 
	"XUSER" VARCHAR2(20 BYTE), 
	"LOGIN_COMPANYCD" VARCHAR2(2 BYTE), 
	"LOGIN_ID" VARCHAR2(20 BYTE), 
	"LOGIN_YMD" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 40 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;

   COMMENT ON COLUMN "PREMIER"."XM606"."COMPANYCD" IS '사업장';
   COMMENT ON COLUMN "PREMIER"."XM606"."TEAMCD" IS '팀코드';
   COMMENT ON COLUMN "PREMIER"."XM606"."SDATE" IS '시작일자';
   COMMENT ON COLUMN "PREMIER"."XM606"."EDATE" IS '종료일자';
   COMMENT ON COLUMN "PREMIER"."XM606"."SORT_" IS '정렬순위';
   COMMENT ON COLUMN "PREMIER"."XM606"."U_TEAMCD" IS '상위부서';
   COMMENT ON COLUMN "PREMIER"."XM606"."XUSER_COMP" IS '메니저_팀장_법인';
   COMMENT ON COLUMN "PREMIER"."XM606"."XUSER" IS '메니저_팀장';
   COMMENT ON TABLE "PREMIER"."XM606"  IS '팀_조직도(APS용)';
