--------------------------------------------------------
--  DDL for Table XM607
--------------------------------------------------------

  CREATE TABLE "PREMIER"."XM607" 
   (	"COMPANYCD" VARCHAR2(2 BYTE), 
	"TEAMCD" VARCHAR2(20 BYTE), 
	"TEAMNM" VARCHAR2(100 BYTE), 
	"TEAM_GBN" VARCHAR2(20 BYTE) DEFAULT '20', 
	"USEYN" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"TEAMNM_SHORT" VARCHAR2(100 BYTE), 
	"REMARK_" VARCHAR2(1024 BYTE), 
	"LOGIN_COMPANYCD" VARCHAR2(2 BYTE), 
	"LOGIN_ID" VARCHAR2(20 BYTE), 
	"LOGIN_YMD" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 40 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;

   COMMENT ON COLUMN "PREMIER"."XM607"."COMPANYCD" IS '사업장';
   COMMENT ON COLUMN "PREMIER"."XM607"."TEAMCD" IS '팀코드';
   COMMENT ON COLUMN "PREMIER"."XM607"."TEAMNM" IS '팀명(Local)';
   COMMENT ON COLUMN "PREMIER"."XM607"."TEAM_GBN" IS '팀 구분 (10:그룹사 20:부문 30:팀 40:부서 )';
   COMMENT ON COLUMN "PREMIER"."XM607"."USEYN" IS '사용유무';
   COMMENT ON COLUMN "PREMIER"."XM607"."TEAMNM_SHORT" IS '팀명(공용)';
   COMMENT ON COLUMN "PREMIER"."XM607"."REMARK_" IS '비고';
   COMMENT ON TABLE "PREMIER"."XM607"  IS '그룹사_통합_팀';
