--------------------------------------------------------
--  DDL for Table XM605
--------------------------------------------------------

  CREATE TABLE "PREMIER"."XM605" 
   (	"COMPANYCD" VARCHAR2(2 BYTE), 
	"TEAMCD" VARCHAR2(6 BYTE), 
	"TEAMNM" VARCHAR2(40 BYTE), 
	"USEYN" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"TEAMNM_ENG" VARCHAR2(50 BYTE), 
	"TEAMNM_SHORT" VARCHAR2(100 BYTE), 
	"LISTORDER" NUMBER, 
	"TEAM_GBN" VARCHAR2(20 BYTE) DEFAULT '20', 
	"MERGE_TEAMCD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 40 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;

   COMMENT ON COLUMN "PREMIER"."XM605"."COMPANYCD" IS '사업장';
   COMMENT ON COLUMN "PREMIER"."XM605"."TEAMCD" IS '팀코드';
   COMMENT ON COLUMN "PREMIER"."XM605"."TEAMNM" IS '팀명(Local)';
   COMMENT ON COLUMN "PREMIER"."XM605"."USEYN" IS '사용유무';
   COMMENT ON COLUMN "PREMIER"."XM605"."TEAMNM_ENG" IS '팀명(공용)';
   COMMENT ON COLUMN "PREMIER"."XM605"."TEAM_GBN" IS '팀 구분 (10:부문 20:팀)';
   COMMENT ON COLUMN "PREMIER"."XM605"."MERGE_TEAMCD" IS '통합조직도상의 팀';
   COMMENT ON TABLE "PREMIER"."XM605"  IS '사업장-팀';
