--------------------------------------------------------
--  DDL for Table XM800
--------------------------------------------------------

  CREATE TABLE "PREMIER"."XM800" 
   (	"YMD" VARCHAR2(8 BYTE), 
	"COINCD" VARCHAR2(30 BYTE), 
	"RATE" NUMBER, 
	"LOGIN_ID" VARCHAR2(20 BYTE), 
	"LOGIN_YMD" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 40 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;

   COMMENT ON TABLE "PREMIER"."XM800"  IS '환율관리테이블';
