--------------------------------------------------------
--  DDL for Table XM900_221109
--------------------------------------------------------

  CREATE TABLE "PREMIER"."XM900_221109" 
   (	"YMD" DATE, 
	"TOCOINCD" VARCHAR2(30 BYTE), 
	"FROMCOINCD" VARCHAR2(30 BYTE), 
	"RATE" NUMBER, 
	"LOGIN_ID" VARCHAR2(20 BYTE), 
	"LOGIN_YMD" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;
