--------------------------------------------------------
--  DDL for Table XM900
--------------------------------------------------------

  CREATE TABLE "PREMIER"."XM900" 
   (	"YMD" DATE, 
	"TOCOINCD" VARCHAR2(30 BYTE), 
	"FROMCOINCD" VARCHAR2(30 BYTE), 
	"RATE" NUMBER, 
	"LOGIN_ID" VARCHAR2(20 BYTE), 
	"LOGIN_YMD" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 40 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREMIER_DAT" ;

   COMMENT ON COLUMN "PREMIER"."XM900"."YMD" IS '기준날짜';
   COMMENT ON COLUMN "PREMIER"."XM900"."TOCOINCD" IS '소스환율';
   COMMENT ON COLUMN "PREMIER"."XM900"."FROMCOINCD" IS '목적환율';
   COMMENT ON COLUMN "PREMIER"."XM900"."RATE" IS '환율';
   COMMENT ON COLUMN "PREMIER"."XM900"."LOGIN_ID" IS '로그인아이디';
   COMMENT ON COLUMN "PREMIER"."XM900"."LOGIN_YMD" IS '로그인날자';
   COMMENT ON TABLE "PREMIER"."XM900"  IS '통화코드별환율테이블';
